### ISSUE TITLE
Qualidade

### ISSUE THREAD

**Issue by giovanifss** [judarlima/Introduction-to-Computer-Science-CS50#1]
Fala ae, 

Tava pensando em fazer esse curso ha um tempo atras. Que que voce ta achando dele? Eh bom mesmo? Vale a pena fazer?

**Comment by judarlima** [comment]
Tô gostando pra caramba Giovani, é puxado mas compensa muito. Os matérias que a galera selecionou para cada disciplina são realmente o que há de melhor e com acesso gratuito.

**Comment by giovanifss** [comment]
Eu tinha comecado ha um tempo atras mas precisei parar pq tava mto corrido. Mas acho que vou fazer entao nas ferias.
